elandome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('i18/', include('django.conf.urls.i18n')),
]

mainapp/urls.py
from django.urls import path
from . import views

app_name='mainapp'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('about', views.about_view, name='about'),
    path('history', views.history_view, name='history'),
    path('contact', views.contact_view, name='contact'),
    path('portfolio', views.portfolio_view, name='portfolio'),
    path('programs', views.programs_view, name='programs'),
    path('edc-community', views.edc_community_view, name='edc-community'),
    path('services', views.services_view, name='services'),
    path('apply', views.application_view, name='application-form'),
    path('news', views.news_view, name='news'),
    path('gallery', views.gallery_view, name='gallery'),
    path('events', views.events_view, name='events'),
    path('resources', views.resources_view, name='resources')
]

mainapp/models.py
from django.db import models
from .countries import COUNTRIES

GENDER = (
    ('- Select -','- Select -'),
    ('Male','Male'),
    ('Female', 'Female'),
    ('Other', 'Other')
)

PROGRAMS = (
    ('- Select -','- Select -'),
    ('Volunteer Services','Volunteer Services'),
    ('Investment supervision, coordination and implementation', 'Investment supervision, coordination and implementation'),
    ('Project Management', 'Project Management'),
    ('Workshops & Training', 'Workshops & Training'),
    ('Career Counselling', 'Career Counselling')
)

TRAVEL_PAX = (
    ('- Select -','- Select -'),
    ('Individual', 'Individual'),
    ('Group', 'Group')
)

PACKAGES = (
    ('- Select -','- Select -'),
    ('Families', 'Families'),
    ('Friends', 'Friends'),
    ('Students', 'Students'),
    ('Employees', 'Employees'),
    ('Individuals', 'Individuals'),
    ('Teachers', 'Teachers')
)

HOW_DID_YOU_HEAR_ABOUT_US = (
    ('- Select -','- Select -'),
    ('Through a friend', 'Through a friend'),
    ('LinkedIn', 'LinkedIn'),
    ('Facebook', 'Facebook'),
    ('Instagram', 'Instagram'),
    ('Twitter', 'Twitter'),
    ('Blog Post', 'Blog Post'),
    ('Word of Mouth', 'Word of Mouth'),
    ('Email', 'Email'),
    ('Online Ad', 'Online Ad'),
    ('Other', 'Other')
)
# Create your models here.
class ContactPage(models.Model):
    full_name = models.CharField(max_length=150)
    email = models.EmailField()
    subject = models.CharField(max_length=150)
    message = models.TextField()
    date_sent = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Contact Page Submissions'

    def __str__(self):
        return f"{self.full_name} - {self.email}"

class VolunteerApplication(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    preferred_name = models.CharField(max_length=100)
    email = models.EmailField()
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state_or_province = models.CharField(max_length=100)
    country_of_origin = models.CharField(max_length=50, choices=COUNTRIES)
    home_phone = models.CharField(max_length=50)
    mobile_phone = models.CharField(max_length=50)
    office_tel = models.CharField(max_length=50)
    gender = models.CharField(max_length=50, choices=GENDER)
    date_of_birth = models.DateField()
    nationality = models.CharField(max_length=50)
    preferred_program = models.CharField(max_length=150, choices=PROGRAMS)


    education_or_experience = models.TextField(blank=True, null=True)
    health_conditions_disabilities = models.TextField(blank=True, null=True)
    personalized_preferrences = models.TextField(blank=True, null=True)
    travel_pack = models.CharField(max_length=50, choices=TRAVEL_PAX,blank=True, null=True)
    preferred_package = models.CharField(max_length=50, choices=PACKAGES,blank=True, null=True)
    duration_of_stay = models.CharField(max_length=100,blank=True, null=True)
    preferred_city = models.CharField(max_length=100,blank=True, null=True)
    date_of_travel = models.DateField(blank=True, null=True)
    do_you_require_further_information = models.TextField(blank=True, null=True)
    how_did_you_hear_about_us = models.CharField(max_length=100, choices=HOW_DID_YOU_HEAR_ABOUT_US, blank=True, null=True)
    any_other_comments = models.TextField(blank=True, null=True)

    # Emergency Contact Details
    emergency_contact_full_name = models.CharField(max_length=100, blank=True, null=True)
    emergency_contact_telephone_no = models.CharField(max_length=50, blank=True, null=True)
    emergency_contact_residential_address = models.CharField(max_length=100, blank=True, null=True)
    emergency_contact_relationship = models.CharField(max_length=100, blank=True, null=True)

    # Referee Contact Details
    referee_contact_full_name = models.CharField(max_length=100, blank=True, null=True)
    referee_contact_organization = models.CharField(max_length=100, blank=True, null=True)
    referee_contact_telephone_no = models.CharField(max_length=50, blank=True, null=True)
    referee_contact_work_address = models.CharField(max_length=100, blank=True, null=True)

    date_of_application = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Application Form Submissions'

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.email} - {self.date_of_application}"

mainapp/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from .models import ContactPage, VolunteerApplication, COUNTRIES, GENDER, TRAVEL_PAX, HOW_DID_YOU_HEAR_ABOUT_US, PROGRAMS, PACKAGES

class ContactPageForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full name", "class":"form-control", "aria-label":"Full name"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email", "class":"form-control", "aria-label":"Email"}))
    subject = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Subject", "class":"form-control", "aria-label":"Subject"}))
    message = forms.CharField(widget=forms.Textarea(attrs={"placholder":"Message", "class":"form-control", "rows": "5"}))
    
    def __init__(self, *args, **kwargs):
        super(ContactPageForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False 

    class Meta:
        model = ContactPage
        fields = '__all__'

class VolunteerApplicationForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"First Name", "class":"form-control", "aria-label":"First Name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Last Name", "class":"form-control", "aria-label":"Last Name"}))
    preferred_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Preferred Name", "class":"form-control", "aria-label":"Preferred Name"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email", "class":"form-control", "aria-label":"Email"}))
    street_address = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Street Address","class":"form-control", "aria-label":"Street Address"}))
    city = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"City", "class":"form-control"}))
    state_or_province = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"State or Province", "class":"form-control"}))
    country_of_origin = forms.ChoiceField(choices=COUNTRIES, widget=forms.Select(attrs={"class":"form-control"}))
    home_phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Home Phone", "class":"form-control"}))
    mobile_phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Mobile Phone", "class":"form-control"}))
    office_tel = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Office Tel.", "class":"form-control"}))
    gender = forms.ChoiceField(choices=GENDER, widget=forms.Select(attrs={"class":"form-control", "class":"form-control"}))
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={"class":"form-control", "id":"datepicker", "placeholder":"mm/dd/yyyy"}))
    nationality = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Nationality"}))
    preferred_program = forms.ChoiceField(choices=PROGRAMS, widget=forms.Select(attrs={"class":"form-control", "placeholder":"Preferred Program"}))


    education_or_experience = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control", "placeholder":"Add your resume here. 700 words max.", "rows":"7"}), required=False)
    health_conditions_disabilities = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control", "rows":"3", "placeholder":"Health conditions, disabilities etc."}), required=False)
    personalized_preferrences = forms.CharField(widget=forms.Textarea(attrs={"placeholder":"Type here...", "rows":"3"}), required=False)
    travel_pack = forms.ChoiceField(choices=TRAVEL_PAX, widget=forms.Select(attrs={"class":"form-control"}), required=False)
    preferred_package = forms.ChoiceField(choices=PACKAGES, widget=forms.Select(attrs={"class":"form-control"}), required=False)
    duration_of_stay = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Duration of stay", "class":"form-control"}), required=False)
    preferred_city =forms.CharField(widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Preferred city"}), required=False)
    date_of_travel = forms.DateField(widget=forms.DateInput(attrs={"class":"form-control", "id":"datepicker2", "placeholder":"mm/dd/yyyy"}), required=False)
    do_you_require_further_information = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control", "placeholder":"Type here...", "rows":"3"}), required=False)
    how_did_you_hear_about_us = forms.ChoiceField(choices=HOW_DID_YOU_HEAR_ABOUT_US, widget=forms.Select(attrs={"class":"form-control"}), required=False)
    any_other_comments = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control", "placeholder":"Type here...", "rows":"3"}), required=False)

    emergency_contact_full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full Name", "class":"form-control"}), required=False)
    emergency_contact_telephone_no = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Telephone No.", "class":"form-control"}), required=False)
    emergency_contact_residential_address = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Residential Address", "class":"form-control"}), required=False)
    emergency_contact_relationship = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Relationship", "class":"form-control"}), required=False)

    referee_contact_full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full Name", "class":"form-control"}), required=False)
    referee_contact_organization = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Organization", "class":"form-control"}), required=False)
    referee_contact_telephone_no = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Telephone No.", "class":"form-control"}), required=False)
    referee_contact_work_address = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Work Address", "class":"form-control"}), required=False)


    def __init__(self, *args, **kwargs):
        super(VolunteerApplicationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = VolunteerApplication
        fields = '__all__'

mainapp/views.py
from django.shortcuts import redirect, render
from .forms import ContactPageForm, VolunteerApplicationForm
from datetime import datetime, timezone
from django.utils.translation import gettext as _
from django.contrib import messages
# Create your views here.

def home_view(request):
    active = 'active'
    context = {'active':active}
    return render(request, 'mainapp/index.html', context)

def about_view(request):
    active = 'active'
    context = {'active':active}
    return render(request, 'mainapp/about.html', context)

def history_view(request):
    return render(request, 'mainapp/history.html')

def contact_view(request):
    if request.method == 'POST':
        form = ContactPageForm(request.POST or None)
        if form.is_valid():
            pass
            # form.save()
            # redirect('mainapp:contact')
            # messages.success(request, 'Your details were submitted successfully!')
            # form = ContactPageForm()
        else:
            messages.warning(request, 'Please correct the errors below.')
    else:
        form = ContactPageForm()
    active = 'active'
    context = {
        'active':active,
        'form':form
        }
    return render(request, 'mainapp/contact.html', context)

def portfolio_view(request):
    active = 'active'
    context = {'active':active}
    return render(request, 'mainapp/portfolio.html', context)

def programs_view(request):
    active = 'active'
    context = {'active':active}
    return render(request, 'mainapp/programs.html', context)

def edc_community_view(request):
    return render(request, 'mainapp/edc-community.html')

def services_view(request):
    active = 'active'
    context = {'active':active}
    return render(request, 'mainapp/services.html', context)

def application_view(request):
    if request.method == 'POST':
        form = VolunteerApplicationForm(request.POST or None)
        if form.is_valid():
            pass
            # form.save()
            # redirect('mainapp:application-form')
            # messages.success(request, 'Your details were submitted successfully!')
            form=VolunteerApplicationForm()
        else:
            messages.warning(request, 'Please correct the errors below.')
    else:
        form = VolunteerApplicationForm()
    active = 'active'
    context = {
        'active':active,
        'form':form
    }
    return render(request, 'mainapp/application-form.html', context)

def news_view(request):
    return render(request, 'mainapp/news.html')

def gallery_view(request):
    return render(request, 'mainapp/gallery.html')

def events_view(request):
    return render(request, 'mainapp/events.html')

def resources_view(request):
    return render(request, 'mainapp/resources.html')

mainapp/templates/mainapp/footer.html
{% load i18n %}
<div style="background-color:#014F42;">
    <div class="container d-none d-sm-block">
        <footer class="py-5">
            <div class="row">
                <div class="col-md-3 mb-3">
                    <p class="footer-title">{% trans "ABOUT US" %}</h5>
                    <div class="pt-3">
                        <p class="footer-text"><a href="{% url 'mainapp:contact' %}" style="color:#fff;text-decoration:none">{% trans "Contact Us" %}</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:services' %}" style="color:#fff;text-decoration:none">{% trans "How we run" %}</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:about' %}" style="color:#fff;text-decoration:none">{% trans "Structure and People" %}</a></p>
                    </div>
                </div>

                <div class="col-md-3  mb-3">
                    <p class="footer-title">{% trans "RESOURCES" %}</h5>
                    <div class="pt-1">
                        <p class="footer-text"><a href="{% url 'mainapp:news' %}" style="color:#fff;text-decoration:none;">{% trans "Media Center" %}</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:contact' %}#faqs" style="color:#fff;text-decoration:none;">FAQs</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:resources' %}" style="color:#fff;text-decoration:none;">Resources</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:edc-community' %}" style="color:#fff; text-decoration:none">{% trans "Our Community" %}</a></p>
                    </div>
                </div>

                <div class="col-md-3 mb-3">
                    <p class="footer-title">{% trans "GET INVOLVED" %}</h5>
                    <div class="pt-1">
                        <p class="footer-text"><a href="{% url 'mainapp:programs' %}" style="color:#fff;text-decoration:none;">{% trans "Our Programs" %}</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:application-form' %}"></a>{% trans "Volunteer with Us" %}</p>
                    </div>
                </div>

                <div class="col-md-3 mb-3">
                    <p class="footer-title">{% trans "LATEST" %}</h5>
                    <div class="pt-1">
                        <p class="footer-text"><a href="{% url 'mainapp:news' %}" style="color:#fff;text-decoration:none;">News</a></p>
                        <p class="footer-text"><a href="https://www.facebook.com/profile.php?id=100086623486138" target="_blank" style="text-decoration: none;color:#fff;">Facebook</a> <i class="fa fa-external-link"></i></p>
                        <p class="footer-text"><a href="https://twitter.com/elan_dome" target="_blank" style="text-decoration: none;color:#fff;">Twitter</a> <i class="fa fa-external-link"></i></p>
                        <p class="footer-text"><a href="http://www.instagram.com/elandome_consultants" target="_blank" style="text-decoration: none;color:#fff;">Instagram</a> <i class="fa fa-external-link"></i></p>
                        <p class="footer-text"><a href="https://www.linkedin.com/company/elan-dome-consultants/" target="_blank" style="text-decoration: none;color:#fff;">LinkedIn</a> <i class="fa fa-external-link"></i></p>
                    </div>
                </div>
            </div>
            <p class="footer-title">{% trans "WORK WITH US" %}</p>
            <p class="footer-text">{% trans "We integrate international experience, community service and supervision and implementation support to ensure that our clients get the best outcomes from our various programs" %}</p>
            <div class="d-flex flex-column flex-sm-row justify-content-between py-4 border-top">
                <p class="footer-bottom-text">Copyright © 2022 | Privacy Policy</p>
            </div>
        </footer>
    </div>

    <!-- Mobile View -->
    <div class="container d-block d-sm-none">
        <footer class="pt-5">
            <div class="row">
                <div class="col-md-3 mb-3">
                    <p class="footer-title">ABOUT US</h5>
                    <div class="pt-1">
                        <p class="footer-text"><a href="{% url 'mainapp:contact' %}" style="color:#fff;text-decoration:none">Contact Us</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:services' %}" style="color:#fff;text-decoration:none">How we run</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:about' %}" style="color:#fff;text-decoration:none">Structure and People</a></p>
                    </div>
                </div>

                <div class="col-md-3  mb-3">
                    <p class="footer-title">RESOURCES</h5>
                    <div class="pt-1">
                        <p class="footer-text"><a href="{% url 'mainapp:news' %}" style="color:#fff;text-decoration:none;">Media Center</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:contact' %}#faqs" style="color:#fff;text-decoration:none;">FAQs</a></p>
                        <!--<p class="footer-text">Human Rights Courses</p> -->
                        <p class="footer-text"><a href="{% url 'mainapp:edc-community' %}" style="color:#fff; text-decoration:none">Our Community</a></p>
                    </div>
                </div>

                <div class="col-md-3 mb-3">
                    <p class="footer-title">GET INVOLVED</h5>
                    <div class="pt-1">
                        <p class="footer-text"><a href="{% url 'mainapp:programs' %}" style="color:#fff;text-decoration:none;">Our Programs</a></p>
                        <p class="footer-text"><a href="{% url 'mainapp:application-form' %}"></a>Volunteer with Us</p>
                    </div>
                </div>

                <div class="col-md-3 mb-3">
                    <p class="footer-title">LATEST</h5>
                    <div class="pt-1">
                        <p class="footer-text"><a href="{% url 'mainapp:news' %}" style="color:#fff;text-decoration:none;">News</a></p>
                        <p class="footer-text"><a href="https://www.facebook.com/profile.php?id=100086623486138" target="_blank" style="text-decoration: none;color:#fff;">Facebook</a> <i class="fa fa-external-link"></i></p>
                        <p class="footer-text"><a href="https://twitter.com/elan_dome" target="_blank" style="text-decoration: none;color:#fff;">Twitter</a> <i class="fa fa-external-link"></i></p>
                        <p class="footer-text"><a href="http://www.instagram.com/elandome_consultants" target="_blank" style="text-decoration: none;color:#fff;">Instagram</a> <i class="fa fa-external-link"></i></p>
                        <p class="footer-text"><a href="https://www.linkedin.com/company/elan-dome-consultants/" target="_blank" style="text-decoration: none;color:#fff;">LinkedIn</a> <i class="fa fa-external-link"></i></p>
                    </div>
                </div>
            </div>
            <p class="footer-title">WORK WITH US</p>
            <p class="footer-text">We integrate international experience, community service and supervision and implementation support to ensure that our clients get the best outcomes from our various programs</p>
            <div class="d-flex flex-column flex-sm-row justify-content-between py-4 border-top">
                <p class="footer-bottom-text">Copyright © 2022 | Privacy Policy</p>
                
            </div>
        </footer>
    </div>
    <!-- End of Mobile View -->
</div>

mainapp/templates/mainapp/navbar.html
{% load static %}
{% load i18n %}

<nav class="navbar navbar-expand-lg bg-white fixed-top py-2">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/elandomelogo.png' %}" alt="elandome logo" style="height:70px;width:auto"/>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-2">
                <li class="nav-item">
                    <a class="nav-link px-2 navlinkbold {{active}}" aria-current="page" href="{% url 'mainapp:home' %}">{% trans "Home" %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link px-2 navlinkbold dropdown-toggle {{active}}" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        {% trans "Who We Are" %}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'mainapp:about' %}">{% trans "About Us" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'mainapp:history' %}">{% trans "Our History" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'mainapp:edc-community' %}">{% trans "EDC Community" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'mainapp:gallery' %}">{% trans "Gallery" %}</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-2 navlinkbold {{active}}" href="{% url 'mainapp:services' %}">{% trans "Services" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-2 navlinkbold {{active}}" href="{% url 'mainapp:programs' %}">{% trans "Programs" %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link px-2 navlinkbold dropdown-toggle {{active}}" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        {% trans "Latest" %}
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'mainapp:news' %}">{% trans "News" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'mainapp:events' %}">{% trans "Events" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'mainapp:resources' %}">{% trans "Resources" %}</a></li>
                    </ul>
                </li>
                <span class="d-block d-sm-none"><div class="pb-2"></div></span>
                <span class="d-none d-sm-block"><span class="">&nbsp;&nbsp;</span></span>
                <li class="nav-item">
                    <a class="d-grid d-md-block " href="{% url 'mainapp:application-form' %}" style="text-decoration: none;color:#fff;">
                        <button class="btn btn-primary" style="background-color: #cc3e18;border:none;" type="button">
                            <span style="font-size:14px;line-height: 20px;font-weight:bold">{% trans "Join Us" %}</span>
                        </button>
                    </a>
                </li>
                <span class="d-block d-sm-none"><div class="pb-3"></div></span>
                <span class="d-none d-sm-block"><span class="">&nbsp;&nbsp;</span></span>
                <li class="nav-item">
                    <a class="d-grid d-md-block " href="{% url 'mainapp:contact' %}" style="text-decoration: none;color:#fff;">
                        <button class="btn btn-primary" style="background-color: #014f42;border:none;" type="button">
                            <span style="font-size:14px;line-height: 20px;font-weight: bold;">{% trans "Get in touch - it's free" %}</span>
                        </button>
                    </a>
                </li>
                <span class="d-block d-sm-none"><div class="pb-1"></div></span>
            </ul>
            {% get_current_language as LANGUAGE_CODE %}
            <form class="d-flex" method="post" action="{% url 'set_language' %}">
                {% csrf_token %}
                <input type="hidden" class="form-control me-2" name="next" value="{{ redirect_to }}" style="font-size: 13px;padding: 7px 15px !important;">
                <select name="language" id="" class="form-control" style="font-size: 13px;padding: 7px !important;">
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                    <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected{% endif %}
                        style="font-size:13px;">{{ language.name|title }} ({{ language.code|upper }})</option>
                    {% endfor %}
                </select>&nbsp;<br>
                <button class="btn " type="submit" style="font-size: 13px;padding: 0.375rem 0.75rem !important;background-color: #cc3e18;border-color: #cc3e18;color:white"><b>Go</b></button>
              </form>
            
            <!-- <li class="nav-item">
                {% get_current_language as LANGUAGE_CODE %}
                <form class="d-flex" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" class="form-control me-2" name="next" value="{{ redirect_to }}" style="font-size: 13px;padding: 7px 15px !important;">
                    <select name="language" id="" class="form-control" style="font-size: 13px;">
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                        <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected{% endif %}
                            style="font-size:13px;">{{ language.name_local }} ({{ language.code }})</option>
                        {% endfor %}
                    </select>&nbsp;<br>
                    <button class="btn " type="submit" style="font-size: 13px;padding: 5px 12px !important;background-color: #0d6efd;border-color: #0d6efd;color:white"><b>Go</b></button>
                </form>
            </li> -->
        </div>
    </div>
</nav>